// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTR20Z.Models;

namespace NTR20Z.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20201213222925_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NTR20Z.Models.ActivityBis", b =>
                {
                    b.Property<int>("activityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("classgroupID")
                        .HasColumnType("int");

                    b.Property<int?>("roomID")
                        .HasColumnType("int");

                    b.Property<int?>("slotID")
                        .HasColumnType("int");

                    b.Property<int?>("subjectID")
                        .HasColumnType("int");

                    b.Property<int?>("teacherID")
                        .HasColumnType("int");

                    b.HasKey("activityID");

                    b.HasIndex("classgroupID");

                    b.HasIndex("roomID");

                    b.HasIndex("slotID");

                    b.HasIndex("subjectID");

                    b.HasIndex("teacherID");

                    b.ToTable("ActivityBis");
                });

            modelBuilder.Entity("NTR20Z.Models.Classgroup", b =>
                {
                    b.Property<int>("classgroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("classgroupID");

                    b.ToTable("Classgroup");
                });

            modelBuilder.Entity("NTR20Z.Models.Room", b =>
                {
                    b.Property<int>("roomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("roomID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("NTR20Z.Models.Slot", b =>
                {
                    b.Property<int>("slotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("slotID");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("NTR20Z.Models.Subject", b =>
                {
                    b.Property<int>("subjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("subjectID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("NTR20Z.Models.Teacher", b =>
                {
                    b.Property<int>("teacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("teacherID");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("NTR20Z.Models.ActivityBis", b =>
                {
                    b.HasOne("NTR20Z.Models.Classgroup", "Classgroup")
                        .WithMany("Activities")
                        .HasForeignKey("classgroupID");

                    b.HasOne("NTR20Z.Models.Room", "Room")
                        .WithMany("Activities")
                        .HasForeignKey("roomID");

                    b.HasOne("NTR20Z.Models.Slot", "Slot")
                        .WithMany("Activities")
                        .HasForeignKey("slotID");

                    b.HasOne("NTR20Z.Models.Subject", "Subject")
                        .WithMany("Activities")
                        .HasForeignKey("subjectID");

                    b.HasOne("NTR20Z.Models.Teacher", "Teacher")
                        .WithMany("Activities")
                        .HasForeignKey("teacherID");
                });
#pragma warning restore 612, 618
        }
    }
}
